name: C/Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: download criterion
      run: curl -o criterion.tar.xz https://github.com/Snaipe/Criterion/releases/download/v2.4.1/criterion-2.4.1-linux-x86_64.tar.xz 
    - name: setup criterion
      run: tar -xvf criterion.tar.xz -C /usr/ --strip-components=1

    - name: setup libraries
      run: sudo apt install libsdl2-dev libsdl2-image-dev

    - name: make all
      run: make all
    - name: make check
      run: make check
