name: C/Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: setup libraries
      run: sudo apt install libsdl2-dev libsdl2-image-dev
    
    - name: make -B VERBOSE=1 all
      run: make -B VERBOSE=1 all
    - name: make -B VERBOSE=1 test
      run: make -B VERBOSE=1 test
