name: C/Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: download criterion
      run: wget https://github.com/Snaipe/Criterion/releases/download/v2.4.1/criterion-2.4.1-linux-x86_64.tar.xz 
    - name: setup criterion
      run: sudo tar -xvf criterion-2.4.1-linux-x86_64.tar.xz -C /usr/ --strip-components=1

    - name: setup libraries
      run: sudo apt install -y libsdl2-dev libsdl2-image-dev
    
    - name: make -B VERBOSE=1 all
      run: make -B VERBOSE=1 all
    - name: make -B VERBOSE=1 test
      run: make -B VERBOSE=1 test

