name: C/Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: setup libraries
      run: sudo apt install libsdl2-dev 
    
    - name: make all
      run: make all
    - name: make check
      run: make check
